project:
  type: book
  output-dir: docs

book:
  title: "BSc Thesis Information"
  sidebar:
    logo: uvt.png
  chapters:
    - index.qmd
    - part: process.qmd
      chapters:
        - preparation.qmd
        - proposal.qmd
        #- introduction.qmd
        #- methods.qmd
        #- results.qmd
        #- discussion.qmd
        #- abstract.qmd
    - materials.qmd
    - part: "Group Meetings"
      chapters:
        - meeting1.qmd
        - meeting2.qmd
        - meeting3.qmd
    - individual.qmd
    - guidelines.qmd
    - contact.qmd
    - faq.qmd
  page-footer: "by Lucija Sorić &copy; Tilburg University<br>last updated 14/09/26"

bibliography: references.bib
csl: apa.csl

format:
  html:
    theme:
      light: [simplex, custom.scss]
      dark: [darkly, custom-dark.scss]
    include-after-body: toggle-move.html
  pdf:
    documentclass: scrreprt

editor: visual