# Individual Meetings {.unnumbered}

After receiving written feedback on different parts of your thesis, you can [book a meeting](https://tidycal.com/l-soric) to further discuss the feedback in person.

These meetings are optional, but *highly recommended*. In the meeting, you can ask about anything you find unclear about the feedback, something you wanted feedback on but did not get, advice, etc.

You can also use these opportunities to ask any other questions you might have, such as issues with motivation, special circumstances, etc.

## Booking Link and Location

### Link

Please use this link to book the meetings: <https://tidycal.com/l-soric>.

This way, you can book any time slot you want\*, and you do not have to let me know of your intention to do so.

\* *I will add more time slots every week. In case there are no available time slots, wait a few days before letting me know.*

### Location

By default, all booked meetings are **in person**. Upon booking, I will let you know where exactly (i.e., which building/room) we will be meeting. However, in case of special circumstances, you can let me know to move the meeting online. There is an option to do so during the booking process. In case of my own special circumstances, I will let you know ASAP about the change in plans.

## Number of Meetings

You are allowed to book **three** (3) meetings to discuss written thesis feedback. However, if you would like to discuss anything else regarding the thesis process - that is not directly related to your written work - *please feel free to book additional meetings*.
